### ISSUE TITLE
Error when trying to add new device to pool

### ISSUE THREAD

**Issue by demizer** [koverstreet/bcachefs-tools#100]
Hello,

I have a six disk pool where one of my devices failed. The mount was formatted using the following command:

```
bcachefs format --discard --compression zstd --group hdds \
    /dev/disk/by-id/ata-ST6000VN001-2BB186_ZR11JBDV \
    /dev/disk/by-id/ata-ST6000VN001-2BB186_ZR11JBCN \
    /dev/disk/by-id/ata-ST8000DM004-2CX188_WCT0AZ6B \
    /dev/disk/by-id/ata-ST3000DM008-2DM166_ZA50G8L1 \
    /dev/disk/by-id/ata-ST3000DM008-2DM166_Z504L42L \
    /dev/disk/by-id/ata-ST3000DM001-1ER166_Z502TSH6 \
    --group ssds /dev/disk/by-id/nvme-WDS100T3X0C-00SJG0_204181800486 \
    --foreground_target=ssds --background_target=hdds \
    --promote_target=ssds --data_replicas=2 --metadata_replicas=2 --label=Bigdata
```

The 1ER166 device completely disappeared and the mount went read only at runtime. The only way I was able to recover the mount was to reboot and mount with "-o rw,very_degraded". I used this FS for a few weeks while waiting for the time to add the new disk to my system. 

Unfortunately, I am now unable to add the new device to the pool:

The device: Seagate Iron Wolf 8TB HDD (marked /dev/sdf)

The new device is un-formatted.

```
sudo bcachefs device set-state failed /dev/disk/by-id/ata-ST3000DM001-1ER166_Z502TSH6 /mnt/data
sudo bcachefs device remove 5 /mnt/data (the failed device, took 10 minutes)
sudo bcachefs device add /mnt/data /dev/sdf -f

read_file_u64: error parsing options/block_size (got 4.0k)           (<--- THE ERROR --->)

```

The fs still mounts just fine, and the data seems fine, but I am unable to add my new device.

System details

Distro: Arch Linux
linux-bcachefs-git version: v5.15.11.arch2.r1045987.0f2596564327-1
bcachefs-tools-git version:  816-1
kernel: Linux lithium 5.15.11-arch2-1-bcachefs-git-384112-g0f2596564327 #1 SMP PREEMPT Tue, 28 Dec 2021 04:43:43 +0000 x86_64 GNU/Linux
bcachfs version: bcachefs tool version v0.1-436-g07b1801 (I do not think this is being set correctly during build)

**Comment by koverstreet** [comment]
Update your tools

**Comment by demizer** [comment]
I did.

```
$ git log -n 1
commit 07b18011cc885f0ef5cadc299d0321322f442388 (HEAD -> master, origin/master, origin/HEAD)
Author: Kent Overstreet <kent.overstreet@gmail.com>
Date:   Tue Dec 21 23:42:46 2021 -0500

    Update bcachefs sources to f9d2e809a8 bcachefs: Turn encoded_extent_max into a regular option
```

This version being reported by the bcachefs tool is coming from here: https://github.com/koverstreet/bcachefs-tools/blob/master/Makefile#L38

```
$ git describe --dirty=+
v0.1-436-g07b1801

```

I can see it in the build log:

```
-DVERSION_STRING='"v0.1-436-g07b1801"' 
```

I don't know how else to check to ensure I am using the latest.

**Comment by koverstreet** [comment]
Looks like I hadn't run the right test, I'm seeing it now

**Comment by YellowOnion** [comment]
Related to https://github.com/koverstreet/bcachefs/commit/ccbac708df6e6655c762225a1a865df0f9fcde23#diff-b96a9b8f98ce2645c3c554fc68ee84f43354c2401bb0e42a65f7ce113702575cL90-R96 I assume?

Perhaps machine readable options should be perserved, and a human readable option added?

**Comment by koverstreet** [comment]
Fixed with the latest kernel and -tools commits
