### ISSUE TITLE
There might be a bug in adding a device?

### ISSUE THREAD

**Issue by nerkinh** [koverstreet/bcachefs-tools#108]
I formatted a few drives to test bcachefs. Evacuating a drive works like a charm, but adding a device always yields the following error:

`blocksize too small: 8, must be greater than device blocksize 512`

I know that all of my drives have the same sector size and `bcachefs show-super` tells me that the block size for the filesystem is `4.0k`. This is confusing because there should not be any problems. I noted that the number `8` is not random (I think it was 0 in previous testing a long time ago, on same drives) but a factor of `4.0k`. I started perusing the source code and by making the following change to the file `cmd_device.c`, line `122`:

before: 
`read_file_u64(fs.sysfs_fd, "options/block_size"));`

after: 
`read_file_u64(fs.sysfs_fd, "block_size"));`

It seems that the `block_size` inside options is the multiple of 512 sized sectors, while the upper directory contains the real block size for the filesystem. This change allowed me to add devices and everything functions perfectly!

I thought about posting a pull request to change this but decided that doing so wasn't the best approach. I do not have kernel engineering experience (neither C language or specific development standards) and I do not know if that is even the proper fix for the problem. Perhaps one of those variables is in the process of being deprecated and that's why the tool behaves like it does. However, without this modification I just could not add any devices to an existing filesystem. It was a genuine problem for me and for which I think there should be an upstream solution.

**Comment by iav** [comment]
Got the same:
```
bcachefs device add /srv/downloads --label=hdd /dev/sdb1
blocksize too small: 512, must be greater than device blocksize 4096

 bcachefs version
1.25.3

uname -a
Linux m1 6.16.0-rc7-edge-rockchip64 #1 SMP PREEMPT Sun Jul 20 22:18:33 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux

```
HDD  have 4096 bytes physical sector size:
```
smartctl -i /dev/sdb
smartctl 7.4 2023-08-01 r5530 [aarch64-linux-6.16.0-rc7-edge-rockchip64] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Western Digital AV-GP (AF)
Device Model:     WDC WD20EURX-63T0FY0
Serial Number:    WD-WCC4M1990526
LU WWN Device Id: 5 0014ee 209d1235d
Firmware Version: 80.00A80
User Capacity:    2,000,398,934,016 bytes [2.00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    5400 rpm
Device is:        In smartctl database 7.3/5528
ATA Version is:   ACS-2 (minor revision not indicated)
SATA Version is:  SATA 3.0, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Fri Jul 25 20:13:05 2025 EEST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
```

How should it be workarounded?
