### ISSUE TITLE
Compilation error when -Werror=format-security

### ISSUE THREAD

**Issue by nightfog-git** [koverstreet/bcachefs-tools#115]
If -Wformat and -Werror=format-security are used, the compilation fails. I believe this should fix that.

[format-security.txt](https://github.com/koverstreet/bcachefs-tools/files/8403336/format-security.txt)

**Comment by koverstreet** [comment]
Just fixed :)

**Comment by firestack** [comment]
for posterity: duplicate of https://github.com/koverstreet/bcachefs/issues/398
