### ISSUE TITLE
mkfs: Unable to write superblock

### ISSUE THREAD

**Issue by Polluktus** [koverstreet/bcachefs-tools#126]
mkfs on fresh 50GB nvme partition give errors:
```
# ./mkfs.bcachefs /dev/nvme0n1p5
[...]
initializing new filesystem
going read-write
initializing freespace
Unable to write superblock to sufficient devices (from 0x56173c7ff1b1s)
fatal error - emergency read only
mounted version=backpointers opts=noinodes_use_key_cache
```
full output https://0x0.st/ou7G.log
tools version/commit: [ff2ebf3f75814bc45353013782ebeb1556adfc05](https://evilpiepirate.org/git/bcachefs-tools.git/commit/?id=ff2ebf3f75814bc45353013782ebeb1556adfc05)

however i can mount normally without any problem

**Comment by colttt** [comment]
hello I had the same issue, please try `bcachefs tool version v0.1-542-gb4afc1f` which should be the latest master version at the moment

**Comment by Polluktus** [comment]
yep, it's fixed, thanks
