### ISSUE TITLE
Cannot mount using the mount command anymore

### ISSUE THREAD

**Issue by nerkinh** [koverstreet/bcachefs-tools#138]
Hello,

I have been using bcachefs for some time now and the latest updates have done something to the mounting procedure. Previously, I have used the following command to mount my two-drive system:

`sudo mount -t bcachefs -o noatime,errors=continue,verbose /dev/disk1:/dev/disk2 /mnt/mountpoint`

Alas, this command does not work for me anymore and what I get as a response is the following:

```
error: invalid value 'mount' for '<UUID>': invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `m` at 1

For more information, try '--help'.
```

I do not know what this exactly means. I have ever only used `uuid` when mounting using fstab, but from what I remember bcachefs was not greatly compatible with this syntax because of multiple disks and the fstab parser (using `:` as the delimiter). How do I mount my disks again? If uuid is the way forward for mounting, what uuid do I use? One of the disks, the external uuid, ...?

Thank you very much for your work on bcachefs, I will live through these growing pains.

**Comment by fougner** [comment]
That's a bug which is fixed in f2ab6e552d311f585e95190075f90b2dd916055d.
