### ISSUE TITLE
Fatal error when mounting returns exit code 0

### ISSUE THREAD

**Issue by CorrosiveTruths** [koverstreet/bcachefs-tools#154]
e.g. mount.bcachefs -v UUID=xx -o nofail /store && echo $?

Will fail to mount the fs with ERROR - bcachefs_rust::cmd_mount: Fatal error: Operation not permitted.

However, it will also return 0. If you have it set to auto mount, you get:

ERROR - bcachefs_rust::cmd_mount: Fatal error: Operation not permitted
/path                   : successfully mounted

**Comment by koverstreet** [comment]
I believe you fixed this :)

**Comment by CorrosiveTruths** [comment]
> I believe you fixed this :)

Hi @koverstreet, I think I've confused the issue with my example.

The issue here is that mount.bachefs returns exit code 0 even when it fails to mount.

e.g. mount bcachefs versus ext4
```
#mount -t bcachefs /dev/null /tmp; echo Exit code $?
ERROR - bcachefs_rust::cmd_mount: Fatal error: "Input/output error"
bcachefs (/dev/null): error reading default superblock: IO error: -5bcachefs (/dev/null): error reading superblock: IO error: -5Exit code 0
# mount -t ext4 /dev/null /tmp; echo Exit code $?
mount: /tmp: /dev/null is not a block device.
       dmesg(1) may have more information after failed mount system call.
Exit code 32
```

Compare to

**Comment by koverstreet** [comment]
That same example works for me, are you sure you're on the latest version?

**Comment by CorrosiveTruths** [comment]
> That same example works for me, are you sure you're on the latest version?

I get exit code 1 when compiling directly from a fresh git clone. Sorry about that!
