### ISSUE TITLE
The released 1.3.1 tarball is empty

### ISSUE THREAD

**Issue by berolinux** [koverstreet/bcachefs-tools#170]
The release tarball, [https://evilpiepirate.org/bcachefs-tools/bcachefs-tools-1.3.1.tar.zst](https://evilpiepirate.org/bcachefs-tools/bcachefs-tools-1.3.1.tar.zst), as linked to from [https://bcachefs.org/](https://bcachefs.org/), is empty (except for a zstd header).

**Comment by koverstreet** [comment]
fixed
