### ISSUE TITLE
Missing line break in a mount error

### ISSUE THREAD

**Issue by Managor** [koverstreet/bcachefs-tools#178]
If I try to mount a drive with `bcachefs mount /dev/nvme1n1` and the drive doesn't contain a bcachefs filesystem, I get an error message with no line break at the end.
```
ERROR - bcachefs_rust::cmd_mount: Fatal error: "invalid_sb_layout"
bcachefs (/dev/nvme1n1): error reading default superblock: Not a bcachefs superblockbcachefs (/dev/nvme1n1): error reading superblock: Not a bcachefs superblock layout[managor@Dark-Machinery [1]~]$ 
```

**Comment by koverstreet** [comment]
Check the latest version, it should be fixed

**Comment by Managor** [comment]
Ah my bad, forgot I had AUR package and needed to manually update.
