### ISSUE TITLE
bcachefs tool list show error

### ISSUE THREAD

**Issue by alkkkj** [koverstreet/bcachefs-tools#197]
Download the lastest bcachefs-tools master code on 12/25,run the following command, then get errors:

./bcachefs format /mnt/bfs_bdev
 ./bcachefs list /mnt/bfs_bdev
bch2_fs_open() bch_fs_open err opening /mnt/bfs_bdev: erofs_nochanges

**Comment by koverstreet** [comment]
this should be fix
