### ISSUE TITLE
Add option to read passphrase from a file

### ISSUE THREAD

**Issue by oz123** [koverstreet/bcachefs-tools#210]
It would be nice if one can read a passphrase from a file.
This is useful for multiple device setups where you only want to type a password once decrypting one
partition and then reading secrets from this file system.
e.g. I have a secret.key in /boot/, I decrypt boot and then continue decryption of some devices:

```
bcachefs unlock -f /boot/secret.key /dev/nvme1n1
```

**Comment by RlndVt** [comment]
Can this be closed as solved?

**Comment by oz123** [comment]
Yep. PR successfully merged.
