### ISSUE TITLE
undefined reference to pwritev2 on musl libc

### ISSUE THREAD

**Issue by xhebox** [koverstreet/bcachefs-tools#213]
Similar to #209. I am adding bcachefs-tools into openwrt with musl libc. And `pwritev2` is not implemented in musl. There is a need for `syscall()` fallback.

**Comment by xhebox** [comment]
https://www.openwall.com/lists/musl/2024/01/18/5 Latest dicussion in the mailing list.

**Comment by rwinkhart** [comment]
MUSL has added pwritev2 support for v1.2.5. I don't have a system to test this with on me right now, but I found this worth noting.

https://www.openwall.com/lists/musl/2024/03/01/2

**Comment by ernsteiswuerfel** [comment]
@rwinkhart Thanks for pointing out!

I updated to musl 1.2.5 on Gentoo which seems to work fine otherwise. But with bcachefs-tools I ran into another build error: #248
