### ISSUE TITLE
Configurable libexec dir?

### ISSUE THREAD

**Issue by freswa** [koverstreet/bcachefs-tools#215]
At ArchLinux we just stumbled over the libexec location. While /usr/libexec works, we usually use something like `/usr/lib/bcachefs-tools/`. Is there any particular reason to kind of hardcode it (and not use `?=` syntax at the beginning of the file) to `LIBEXECDIR=$(PREFIX)/libexec` [here](https://github.com/koverstreet/bcachefs-tools/blob/master/Makefile#L108)?

**Comment by koverstreet** [comment]
That should be fine - please supply a patch and I'll apply it.
