### ISSUE TITLE
Cannot (re)mount filesystems when /tmp/ is not writeable ("kind: ReadOnlyFilesystem, error: PathError")

### ISSUE THREAD

**Issue by SorrelArticulata** [koverstreet/bcachefs-tools#217]
My computer was unable to boot properly today with bcachefs as my root filesystem:

```
# mount -o remount,rw /   <--- this is what my init was running as my rootfs was mounted ro by the initrd
thread '<unnamed>' panicked at src/cmd_mount.rs:105:46:
called `Result::unwrap()` on an `Err` value: Custom { kind: ReadOnlyFilesystem, error: PathError { path: "/tmp/.tmp9z6YZh", err: Os { code: 30, kind: ReadOnlyFilesystem, message: "Read-only file system" } } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```

Workaround:

```
# mount -t tmpfs /tmp
# mount -o remount,rw /  <---- this now succeeds
```

Versions used:

* bcachefs-tools 1.4.0 (git 3070f45d968575efd42ecf44f94427203b2ab62e)
* kernel 6.7.0-rc7 (bcache kernel git 2bf0b0a9dff974cac259ce92d146e7142f472496)
* distro: Void Linux
* init: runit

I suspect this problem was triggered by me updating my distro yesterday.  Something has probably affected the order of mounts so that the rootfs is remounted before a tmpfs is mounted on /tmp.  Editing the order of lines in my /etc/fstab didn't change this.

**Comment by koverstreet** [comment]
Can you try the testing branch of tools?

If that still fails, run with RUST_BACKTRACE=1 (like it says) and post the backtrace here.
