### ISSUE TITLE
Attempting to unlock encrypted partitions results in 100% CPU usage and partition never being unlocked

### ISSUE THREAD

**Issue by Valmar33** [koverstreet/bcachefs-tools#265]
First bad commit is https://github.com/koverstreet/bcachefs-tools/commit/477670f48167cac1b871b061713cc1b594a2a941

With this commit, attempting to unlock a partition results in the process consuming 100% CPU and never actually getting to unlocking the partition. Rather it just stalls forever. Though the process can be cleanly stopped with Ctrl+C.

**Comment by tmuehlbacher** [comment]
This looks like it would be fixed by the second commit in #263

**Comment by Valmar33** [comment]
> This looks like it would be fixed by the second commit in #263

I've tested the MR and it appears to work. Do I close this issue?

**Comment by tmuehlbacher** [comment]
I think that would be fine. I hope to get the fixes merged soon.
Thanks for testing and also for bisecting all the way in the first place. 🙂

**Comment by Valmar33** [comment]
> I think that would be fine. I hope to get the fixes merged soon. Thanks for testing and also for bisecting all the way in the first place. 🙂

It is much easier when it's a userspace tool that doesn't require a bigger series of steps like rebooting and trying to trigger something, heh.

**Comment by JohnRTitor** [comment]
I don't think it should be closed since the patch has not been merged yet. "Closing this as completed" kind of signifies that the bug has been fixed already and the fix is in master, which is not the case here.
